### ISSUE TITLE
sais.md里的代码本地测试一直没通过

### ISSUE THREAD

**Issue by Daiwz92** [riteme/riteme.github.io#83]
sais.md里的代码本地测试一直没通过

**Comment by Daiwz92** [comment]
int test[10] = {1, 5, 3, 4, 5, 0};

    int *sa = SAIS(test, 6, 6);

    for (int i = 0; i < 6; i++) {
        std::cout << sa[i] << " ";
    }
使用这样的比较简单的也不可以 SA[sbucket[S[position[i]]]--] = position[i];这个地方会失败

**Comment by riteme** [comment]
感谢反馈！

现在问题应该已经修复了。你可以在 <https://github.com/riteme/riteme.github.io/commit/40d4a8a59570637c0c077e70eafb8d23368eb53f> 查看需要修改的地方。
